const API='http://127.0.0.1:8000';
const symbols=['TCS','INFY','RELIANCE','HDFCBANK'];
const money=value=>`$${Number(value).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
async function get(path){const response=await fetch(API+path);if(!response.ok)throw Error('Unable to load data');return response.json()}
function renderIndices(items){document.querySelector('#indices').innerHTML=items.map(item=>`<article class="index-card"><p>${item.name}</p><strong>${Number(item.value).toLocaleString()}</strong><span class="change positive">+${item.change}%</span></article>`).join('')}
let stockData=[];
function renderStock(item){const positive=Number(item.change)>=0;return `<article class="stock" data-symbol="${item.symbol}" tabindex="0" role="button"><div class="ticker">${item.symbol.slice(0,1)}</div><div class="stock-info"><strong>${item.symbol}</strong><small>${item.sector} · AI score ${item.ai_score}/100</small></div><div class="stock-price"><strong>${money(item.price)}</strong><small class="${positive?'positive':'negative'}">${positive?'+':''}${item.change}%</small></div></article>`}
async function load(){try{const overview=await get('/api/market/overview');renderIndices(overview.indices);stockData=await Promise.all(symbols.map(symbol=>get('/api/stocks/'+symbol)));document.querySelector('#stocks').innerHTML=stockData.map(renderStock).join('')}catch(error){document.querySelector('#indices').innerHTML='<div class="loading">Backend unavailable. Start FastAPI on port 8000.</div>';document.querySelector('#stocks').innerHTML=''}}
document.querySelector('#themeButton').addEventListener('click',()=>document.body.classList.toggle('light'));load();
document.querySelectorAll('[data-target]').forEach(button=>button.addEventListener('click',()=>document.getElementById(button.dataset.target)?.scrollIntoView({behavior:'smooth',block:'start'})));
document.querySelectorAll('.module-card').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#module-message').textContent=button.dataset.message}));
document.querySelector('#stock-search').addEventListener('input',event=>{const query=event.target.value.toLowerCase();document.querySelector('#stocks').innerHTML=stockData.filter(item=>item.symbol.toLowerCase().includes(query)||item.name.toLowerCase().includes(query)).map(renderStock).join('')||'<div class="loading">No matching stock found.</div>'});
document.querySelector('#stocks').addEventListener('click',async event=>{const row=event.target.closest('[data-symbol]');if(!row)return;const item=await get('/api/stocks/'+row.dataset.symbol+'/ai-analysis');document.querySelector('#dialog-title').textContent=item.symbol+' · '+row.querySelector('.stock-info strong').textContent;document.querySelector('#dialog-score').textContent=item.overall_score+'/100';document.querySelector('#dialog-explanation').textContent=item.explanation;document.querySelector('#dialog-factors').innerHTML='<strong>Why this score</strong><br>✓ '+item.positive_factors.join('<br>✓ ')+'<br><span class="negative">⚠ '+item.risk_factors.join('<br>⚠ ')+'</span>';document.querySelector('#stock-dialog').showModal()});
document.querySelector('.dialog-close').addEventListener('click',()=>document.querySelector('#stock-dialog').close());
